# Riley Garrison
# 9/19/2018
# Project 1

proj1.x: Group.o proj1.o
	g++ -o proj1.x Group.o proj1.o
	rm proj1.o
	rm Group.o

Group.o: Group.cpp Group.h
	g++ -c Group.cpp

proj1.o: proj1.cpp
	g++ -c proj1.cpp
